### ISSUE TITLE
SPIKE: Technology upgrade to Angular 7

### ISSUE THREAD

**Issue by XxChauhanxX** [hashmapinc/Tempus#1013]
Child of #556
As part of this spike, we need to determine the overall Pros and Cons of upgrading to Angular 7, so that there are less challenges in the future. 
Along with this, a thorough analysis on the peripheral technologies to be used with Angular 7 should be. 
A decision log should be maintained for the same, so that it can be referenced in the future if needed.

**Comment by Shobhit2884** [comment]
Features of angular js:-

1).  CLI Prompts:- Added new feature for CLI will prompt users while typing common commands like ng-add or ng-new.

 2). Performance:- Angular team discovered blemish that Angular developer were including the reflect-metadata polyfill in production, which is only needed in development, In order to fix this, part of the update to v7 will automatically remove it from your polyfills.ts file, and then include it as a build step when building your application in JIT mode, removing this polyfill from production builds by default.

3).To speed up the performance new applications will warn when the initial bundle is more than 2MB and will error at 5MB which user can modify it in angular.json file. These budgets align with warnings that can be shown to users taking advantage of Chrome’s Data Saver features.

4). New features:- Angular 7 features visual improvements in Material Design which received a major update in 2018, refresh as well as virtual scrolling, for dynamically loading and unloading parts of the DOM to build high-performing, large lists of data. Also, applications can be fitted with a drag-and-drop capability by importing the DragDropModule or the ScrollingModule

5). Angular Do-Bootstrap:- It's used for bootstrapping modules that need to bootstrap a component. Angular 7 added a new life-cycle hook (ngDoBootstrap) and interface (DoBootstrap).

6).New ng-compiler :- provides an accelerated eight-phase compilation and reduction of large app size approximately 2 times.

7).Splitting of @angular/core:- One of the disadvantages of Angular is its total multipurposeness. It’s a large framework itself automatically provides modules which you probably don’t need, thus team Angular has split @angular/core past the boundaries presented no less than 418 modules.

Source:- https://www.angularminds.com/blog/article/top-10-features-of-angular-7.html
