### ISSUE TITLE
Uploading the same computation twice crashes tempus

### ISSUE THREAD

**Issue by cherrera2001** [hashmapinc/Tempus#175]
Uploading the same computation twice crashes tempus

**Comment by jetinder20** [comment]
I could not reproduce this issue at all when same computation is uploaded again without creating the job instance. However, I could reproduce issue only once when i had created a computation job instance and then uploaded  the same computation. 

Question to you @cherrera2001 , whats the expected behavior in case when computation has job instances(running/suspended both cases) and in case when computation doesn't have computation job instances ?

Should we even allow user to replace the computation at all ? I think we can ask user to delete the existing computation manually and then only allow to upload the same computation to avoid accidental replacement of computations.

**Comment by cherrera2001** [comment]
The expected behavior is that a user must delete a computation with the same name before it can be copied again.

**Comment by jetinder20** [comment]
The changes are on branch - Tempus-175-Same_Computation_upload_bug
