### ISSUE TITLE
Need to Display User Name in Top Bar

### ISSUE THREAD

**Issue by SPParnerkar** [hashmapinc/Tempus#583]
When a User (Customer) logs in to Tempus, 'Business Unit' is displayed as Profile in top right corner. This should be changed to display user name (First Name+Last Name). Displaying user name will improve Tempus' connect with the user.

For Tenant Administrator and System Administrator, roles are displayed. Please consider whether this should also be changed to display user names as well.

Users can anyway see their role and other details by clicking on Profile.

**Comment by shubhamkumargupta** [comment]
Showing First Name + Last Name functionality already exists in Tempus. So when we create SysAdmin or Demo User or Bob if we provide First Name + Last Name while creating user it will show it on top bar with its role. And if we have not provided any kind of name it will only show logged in user role. 

For now what we can do is to show username i.e email address if Name is not provided. Otherwise it will work as present showing First and Last Name.

Showing role in top Bar : it is required for now as when a user clicks on its own profile it doesn't show what is the role of that particular user. If we want to remove it from top bar we need to work on showing some more information on user profile.
